---
- include_vars: 
    file: "{{ansible_os_family}}.yml"

- include_tasks: setup-{{ansible_os_family}}.yml

- name: Install Docker Python
  pip:
    name: "{{item.name}}"
    state: "{{item.state}}"
  vars:
    packages:
    - name: docker
      state: present
  with_items: "{{ packages }}"  

- name: Add vagrant user to dockerd group
  user:
    append: "yes"
    groups: "docker"
    name: "{{ default_user | default('vagrant') }}"

- name: Create Docker directory
  file:
    path: /etc/docker
    state: directory

- name: Customize Dockerd
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json   
    remote_src: no      

- name: Enable Docker Service
  systemd:
    name: docker.service
    enabled: true
    state: started