---

- debug:
    msg: "{{ ansible_distribution }}"

- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"

- include_tasks: setup-{{ansible_os_family | lower }}.yml

- name: Install base packages
  package:
    name : "{{packages_install}}"
    state : present
    update_cache : yes                   

- name: Install Docker Python
  pip:
    name: "{{item.name}}"
    state: "{{item.state}}"
  vars:
    packages:
    - name: docker
      state: present
  with_items: "{{ packages }}"  

- name: Add vagrant user to dockerd group
  user:
    append: "yes"
    groups: "docker"
    name: "{{ default_user | default('vagrant') }}"

- name: Create Docker directory
  file:
    path: /etc/docker
    state: directory

- name: Customize Dockerd
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json   
    remote_src: no      

- name: Enable Docker Service
  systemd:
    name: docker.service
    enabled: true
    state: started