---
- import_tasks: install_docker.yml
  when: asbrl_docker_install_docker

- import_tasks: install_certificates.yml
  when: asbrl_docker_install_certificates

- import_tasks: install_registry.yml
  when: asbrl_docker_install_registry

- import_tasks: install_watchtower.yml
  when: asbrl_docker_install_watchtower