- name: Install Docker key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg 

- name: Add Docker Apt Repository
  apt_repository:
    filename: docker-ce
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
